# .github/workflows/reusable-test-job.yml
name: "Reusable Test Job"

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: npm ci
      
      - name: Test
        run: npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
